/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Graph;
import Classes.Kosaraju;
import DataStructureClasses.SimpleList;
import FileManager.FileManager;
import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author bcsoporte
 */
public class MainInterface extends javax.swing.JFrame {

    // definir las listas globales con los datos necesario de los vertices
    Page1 page1 = new Page1();
    Page2 page2 = new Page2();
    DibujarGrafo dibujarGrafo = new DibujarGrafo();

    /**
     * Creates new form main
     */
    public MainInterface() {
        initComponents();
        setTitle("Pantalla Principal");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
//      setDefaultCloseOperation(EXIT_ON_CLOSE);
//      page1.setSize(410, 320);
//      page1.setLocation(0, 0);
//      content.removeAll();
//      content.add(page1, BorderLayout.CENTER);
//      content.revalidate();
//      content.repaint();

//      Agregar el panel DibujarGrafo a la página
        dibujarGrafo.setSize(650, 440);
        dibujarGrafo.setLocation(0, 0);
        this.content.removeAll();
        this.content.add(dibujarGrafo, BorderLayout.CENTER);
        this.content.revalidate();
        this.content.repaint();

        this.setVisible(true);
    }

    private void displayFromFile(File file) {
        String line;

        try {
            this.graphComponents.setText("");
            FileReader filereader = new FileReader(file);
            BufferedReader reader = new BufferedReader(filereader);

            while ((line = reader.readLine()) != null) {
                // ejemplo: mostrar informacion en un text area
                this.graphComponents.append(line);
                this.graphComponents.append("\n");
                line = reader.readLine();
            }

            reader.close();
            JOptionPane.showMessageDialog(null, "El archivo ha sido cargado exitosamente!");

        } catch (IOException e) {
            e.printStackTrace(System.out);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún archivo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        graphComponents = new javax.swing.JTextArea();
        loadTestBtn = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        openBtn = new javax.swing.JMenuItem();
        modifyButton = new javax.swing.JMenuItem();
        saveMenuBtn = new javax.swing.JMenuItem();
        exitBtn = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 650, 440));

        graphComponents.setColumns(20);
        graphComponents.setRows(5);
        jScrollPane1.setViewportView(graphComponents);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 240, 310));

        loadTestBtn.setText("load");
        loadTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTestBtnActionPerformed(evt);
            }
        });
        bg.add(loadTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 680));

        menu1.setText("Archivo");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        openBtn.setText("Abrir");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });
        menu1.add(openBtn);

        modifyButton.setText("Modify");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });
        menu1.add(modifyButton);

        saveMenuBtn.setText("Guardar");
        saveMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuBtnActionPerformed(evt);
            }
        });
        menu1.add(saveMenuBtn);

        exitBtn.setText("Salir");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        menu1.add(exitBtn);

        menubar.add(menu1);

        setJMenuBar(menubar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
//      crear objeto de tipo filechooser que contendra el archivo txt
        if (evt.getSource() == this.openBtn) {

            FileManager fileManager = new FileManager();
            File file = fileManager.selectFile();

            SimpleList usersList = fileManager.parseUsersFromFile(file);
            SimpleList relationsList = fileManager.parseRelationshipsFromFile(file);

            Graph grafo = new Graph(usersList, relationsList);
            Kosaraju kosaraju = new Kosaraju(grafo);
            this.displayFromFile(file);
        }

    }//GEN-LAST:event_openBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        if (evt.getSource() == this.exitBtn) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed


    private void saveMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuBtnActionPerformed
        if (evt.getSource() == this.saveMenuBtn) {
            FileManager fileManager = new FileManager();
            File file = fileManager.selectFile();
            fileManager.saveFileToTxt(file);
            this.displayFromFile(file);

//          Hacer display directo 
        }
    }//GEN-LAST:event_saveMenuBtnActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu1ActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == this.modifyButton) {
//            FileManager fileManager = new FileManager();
//            File file_prueba = fileManager.selectFile();
//            //fileManager.parseUsersFromFile(file_prueba, ignore);
//            users_list = fileManager.parseUsersFromFile(file_prueba);
//
//            //Probando que la lista global esté funcionando
//            JOptionPane.showMessageDialog(null, "* Lista de usuarios actualizada\n" + users_list.printToString());
        }
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void loadTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTestBtnActionPerformed
        // TODO add your handling code here
        if (evt.getSource() == this.loadTestBtn) {
            String textAreaInput = this.graphComponents.getText();
//            System.out.println(textAreaInput);

            FileManager fileManager = new FileManager();
            fileManager.saveStringToTxt(textAreaInput);
        }

    }//GEN-LAST:event_loadTestBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void runMainGUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel content;
    private javax.swing.JMenuItem exitBtn;
    private javax.swing.JTextArea graphComponents;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadTestBtn;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem modifyButton;
    private javax.swing.JMenuItem openBtn;
    private javax.swing.JMenuItem saveMenuBtn;
    // End of variables declaration//GEN-END:variables
}
