/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bcsoporte
 */
public class mainwind extends javax.swing.JFrame {

    Page1 page1 = new Page1();
    Page2 page2 = new Page2();

    /**
     * Creates new form mainwind
     */
    public mainwind() {
        initComponents();
        setTitle("Pantalla Principal");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        //setDefaultCloseOperation(EXIT_ON_CLOSE);
        page1.setSize(410, 320);
        page1.setLocation(0, 0);
        content.removeAll();
        content.add(page1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        btnPrev.setEnabled(false);
    }

    private void ShowPanel(){}

    private void disableButtons() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea1 = new javax.swing.JTextArea();
        content = new javax.swing.JPanel();
        menubar = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        menuitem1 = new javax.swing.JMenuItem();
        menuitem2 = new javax.swing.JMenuItem();
        menuitem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrev.setText("Previous");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        bg.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        bg.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        txtArea1.setColumns(20);
        txtArea1.setRows(5);
        jScrollPane1.setViewportView(txtArea1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 240));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 410, 320));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 400));

        menubar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        menu1.setText("Archivo");

        menuitem1.setText("Abrir");
        menuitem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem1ActionPerformed(evt);
            }
        });
        menu1.add(menuitem1);

        menuitem2.setText("Guardar");
        menu1.add(menuitem2);

        menuitem3.setText("Salir");
        menuitem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem3ActionPerformed(evt);
            }
        });
        menu1.add(menuitem3);

        menubar.add(menu1);

        setJMenuBar(menubar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem3ActionPerformed
        if (evt.getSource() == menuitem3) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuitem3ActionPerformed

    private void menuitem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem1ActionPerformed
        JFileChooser filechooser = new JFileChooser();
        filechooser.showOpenDialog(filechooser);
        String line;
        try {
            String path = filechooser.getSelectedFile().getAbsolutePath();

            File file = new File(path);
            FileReader filereader = new FileReader(file);
            BufferedReader reader = new BufferedReader(filereader);

            while ((line = reader.readLine()) != null) {
                System.out.println(line);
                txtArea1.append(line);
                txtArea1.append("\n");
                line = reader.readLine();
            }

            reader.close();
            JOptionPane.showMessageDialog(null, "Archivo Cargado con Exito!");

        } catch (IOException excepcion) {
            excepcion.printStackTrace(System.out);
        }
    }//GEN-LAST:event_menuitem1ActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
//        if (evt.getSource() == btnNext) {
//            page2.setVisible(false);
//            page1.setVisible(true);
//            content.add(page1);
//            content.validate();
//            disableButtons();
//        }

        page2.setSize(410, 320);
        page2.setLocation(0, 0);
        content.removeAll();
        content.add(page2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        btnPrev.setEnabled(true);
        btnNext.setEnabled(false);

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        page1.setSize(410, 320);
        page1.setLocation(0, 0);
        content.removeAll();
        content.add(page1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        btnPrev.setEnabled(false);
        btnNext.setEnabled(true);
    }//GEN-LAST:event_btnPrevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainwind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainwind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainwind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainwind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainwind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem menuitem1;
    private javax.swing.JMenuItem menuitem2;
    private javax.swing.JMenuItem menuitem3;
    private javax.swing.JTextArea txtArea1;
    // End of variables declaration//GEN-END:variables
}
