/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Classes.Vertex;
import DataStructureClasses.SimpleList;
import FileManager.ComboBoxAPI;

/**
 *
 * @author bcsoporte
 */
public class Page2 extends javax.swing.JPanel {

    /**
     * Creates new form Page2
     */
    private String userName;
    private int relationIndex;
    private boolean isConfirmed;

    public Page2(SimpleList<Vertex> comboBoxList) {
        initComponents();

        for (int i = 0; i < comboBoxList.getSize(); i++) {
            Vertex v = comboBoxList.getValueByIndex(i);
            String userName = v.getName();
            this.usersComboList.addItem(userName);
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        usersComboList = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        userNameBox1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese el nuevo Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 20));

        usersComboList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        usersComboList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersComboList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersComboListActionPerformed(evt);
            }
        });
        jPanel1.add(usersComboList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Seleccione el destino de relacion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 380, 30));

        userNameBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(userNameBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void usersComboListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersComboListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usersComboListActionPerformed

    public ComboBoxAPI parsePage2() {
        ComboBoxAPI comboAPI = new ComboBoxAPI(this.userName, this.relationIndex, this.isConfirmed);
        return comboAPI;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField userNameBox1;
    private javax.swing.JComboBox<String> usersComboList;
    // End of variables declaration//GEN-END:variables
}
