/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author bcsoporte
 */
public class Page2 extends javax.swing.JPanel {

    /**
     * Creates new form Page2
     */
    public Page2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        label1.setText("This Shit Hard");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        label3.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        label3.setText("Jota Label - Page 2");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        label2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        label2.setText("This Shit Hard");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    // End of variables declaration//GEN-END:variables
}
